import { ArrowLeft, FileText, AlertTriangle } from 'lucide-react';

const EFFECTIVE_DATE = 'June 1, 2025';

const SECTIONS = [
  {
    id: '1',
    title: '1. Acceptance of Terms',
    content: `By downloading, installing, or using the VerifyGH application, website, or SMS verification service (collectively, the "Services"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, you must not use the Services.

VerifyGH Limited ("VerifyGH", "we", "us", or "our") reserves the right to update these Terms at any time. Continued use of the Services after changes are published constitutes acceptance of the revised Terms. We will notify users of material changes via the application or registered email.`,
  },
  {
    id: '2',
    title: '2. Description of Services',
    content: `VerifyGH is a product authentication platform designed to help consumers, retailers, manufacturers, and regulators in Ghana verify the authenticity of products registered in the VerifyGH database.

Our Services include:
• Mobile application (iOS and Android) with QR/barcode scanning
• Web-based product lookup portal
• SMS verification service (send product code to receive authentication reply)
• Manufacturer portal for product registration and analytics
• Counterfeit reporting system

VerifyGH operates in partnership with the Ghana Food and Drugs Authority (FDA) and other regulatory bodies to maintain an accurate product registry.`,
  },
  {
    id: '3',
    title: '3. Accuracy Disclaimer',
    content: `3.1 No Guarantee of Completeness
VerifyGH's database is populated by registered manufacturers and regulatory bodies. Not all products available in Ghana may be listed. A "Not Found" result does not definitively mean a product is counterfeit — it may simply not yet be registered.

3.2 No Medical or Safety Advice
Verification results are informational only and do not constitute medical, pharmaceutical, agricultural, or safety advice. Always consult qualified professionals before using any product, particularly medicines or agro-inputs.

3.3 Manufacturer Responsibility
Product information in our database (expiry dates, FDA approval status, batch numbers) is provided by manufacturers. VerifyGH is not responsible for inaccurate or outdated information submitted by manufacturers.

3.4 System Availability
We strive for high service availability but cannot guarantee uninterrupted access. Verification services may be temporarily unavailable due to maintenance, updates, or technical issues beyond our control.`,
  },
  {
    id: '4',
    title: '4. User Responsibilities',
    content: `As a user of VerifyGH, you agree to:

• Use the Services only for lawful purposes and in accordance with these Terms
• Provide accurate information when submitting counterfeit reports or contact forms
• Not attempt to manipulate, falsify, or corrupt the product registry database
• Not use automated tools, bots, or scripts to access the Services without written permission
• Not impersonate any person, company, or regulatory body
• Not submit false counterfeit reports with the intent to damage a legitimate manufacturer's reputation
• Not attempt to reverse-engineer, decompile, or extract the source code of our applications
• Report genuine concerns through the appropriate channels rather than public defamation`,
  },
  {
    id: '5',
    title: '5. Manufacturer Accounts',
    content: `5.1 Registration
Manufacturers must register and provide accurate company and product information. Providing false information is a breach of these Terms and may constitute fraud under Ghanaian law.

5.2 Product Codes
Verification codes generated by VerifyGH are unique to each product registration. Manufacturers are responsible for the secure application of these codes to physical products and for preventing unauthorised reproduction.

5.3 Account Security
You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. Notify us immediately of any unauthorised account access.

5.4 Suspension
We reserve the right to suspend or terminate manufacturer accounts that violate these Terms, submit fraudulent data, or engage in activities that undermine the integrity of the platform.`,
  },
  {
    id: '6',
    title: '6. Counterfeit Reporting',
    content: `6.1 Good Faith Reporting
Users are encouraged to report suspected counterfeit products. Reports must be submitted in good faith based on reasonable belief. Malicious, knowingly false, or defamatory reports are prohibited.

6.2 Use of Reports
Submitted reports may be shared with Ghana FDA, law enforcement, and relevant manufacturers for investigation purposes. By submitting a report, you consent to this sharing.

6.3 Anonymity
While we collect contact details for follow-up purposes, we will protect the identity of reporters in public-facing communications where feasible and legally permitted.`,
  },
  {
    id: '7',
    title: '7. Intellectual Property',
    content: `All content, trademarks, logos, database structures, algorithms, and software comprising the VerifyGH platform are the exclusive intellectual property of VerifyGH Limited or its licensors.

You are granted a limited, non-exclusive, non-transferable licence to use the Services for their intended purpose. You may not copy, reproduce, distribute, modify, or create derivative works based on any part of the Services without prior written consent.

Product names, brand names, and trademarks visible in the VerifyGH database remain the property of their respective owners.`,
  },
  {
    id: '8',
    title: '8. Limitation of Liability',
    content: `To the maximum extent permitted by applicable Ghanaian law:

• VerifyGH shall not be liable for any direct, indirect, incidental, special, or consequential damages arising from your use of, or inability to use, the Services
• VerifyGH shall not be liable for any loss or damage arising from reliance on verification results, including decisions made regarding product use or purchase
• VerifyGH shall not be liable for harm caused by counterfeit products that were not detected due to database incompleteness
• Our total liability to you for any claim shall not exceed the amount paid by you for the Services in the 12 months preceding the claim (or GH₵ 100 if no amount was paid)

Nothing in these Terms limits liability for death, personal injury caused by negligence, fraud, or any other liability that cannot be excluded by law.`,
  },
  {
    id: '9',
    title: '9. Termination',
    content: `VerifyGH reserves the right to suspend or terminate your access to the Services at any time and without notice if you breach these Terms or engage in conduct detrimental to the platform's integrity.

You may discontinue use of the Services at any time. Deletion of your account does not immediately erase all associated data; data retention follows our Privacy Policy.

Upon termination, all licences granted to you under these Terms will immediately cease.`,
  },
  {
    id: '10',
    title: '10. Privacy',
    content: `Your use of the Services is also governed by our Privacy Policy, which is incorporated into these Terms by reference. Please review our Privacy Policy carefully to understand our data practices.`,
  },
  {
    id: '11',
    title: '11. Governing Law & Disputes',
    content: `These Terms shall be governed by and construed in accordance with the laws of the Republic of Ghana, without regard to conflicts of law principles.

Any dispute arising out of or in connection with these Terms shall first be subject to good-faith negotiation between the parties. If the dispute cannot be resolved within 30 days, it shall be referred to arbitration in Accra, Ghana, under the rules of the Ghana Arbitration Centre.

Nothing in this clause prevents either party from seeking urgent injunctive relief from a court of competent jurisdiction.`,
  },
  {
    id: '12',
    title: '12. Contact Information',
    content: `If you have questions about these Terms, please contact us:

VerifyGH Limited
No. 15 Ebo Street, Cantonments
Accra, Ghana

Email: legal@verifygh.gov.gh
Phone: +233 30 280 0100
Website: www.verifygh.gov.gh`,
  },
];

export default function TermsScreen({ onNavigate }: { onNavigate: (screen: string) => void }) {
  return (
    <div className="min-h-screen bg-gray-50 pb-10">

      {/* ── Header ─────────────────────────────────────────────── */}
      <div className="bg-gray-900 px-5 pt-12 pb-8 rounded-b-[2.5rem] relative overflow-hidden">
        <div className="absolute -top-14 -right-14 w-52 h-52 bg-white/[0.03] rounded-full" />
        <div className="relative z-10">
          <button onClick={() => onNavigate('home')} className="w-10 h-10 bg-white/10 rounded-xl flex items-center justify-center mb-5">
            <ArrowLeft className="w-5 h-5 text-white" />
          </button>
          <div className="flex items-center gap-3 mb-3">
            <div className="w-10 h-10 bg-white/10 rounded-2xl flex items-center justify-center">
              <FileText className="w-6 h-6 text-white/70" />
            </div>
            <div>
              <h1 className="text-xl font-black text-white">Terms of Service</h1>
              <p className="text-white/40 text-xs">Effective: {EFFECTIVE_DATE}</p>
            </div>
          </div>
          <div className="bg-white/10 rounded-xl px-3.5 py-2.5">
            <p className="text-white/70 text-xs leading-relaxed">
              Please read these Terms carefully before using VerifyGH. By using our Services,
              you agree to be legally bound by these Terms.
            </p>
          </div>
        </div>
      </div>

      {/* ── Acceptance notice ───────────────────────────────────── */}
      <div className="px-4 pt-5">
        <div className="bg-amber-50 border border-amber-200 rounded-2xl px-4 py-3.5 flex items-start gap-3 mb-4">
          <AlertTriangle className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" />
          <div>
            <p className="text-xs font-bold text-amber-800">Important Notice</p>
            <p className="text-xs text-amber-700 mt-0.5 leading-relaxed">
              These Terms constitute a legally binding agreement. Using VerifyGH constitutes
              your acceptance of these Terms in full. If you disagree, please discontinue use immediately.
            </p>
          </div>
        </div>
      </div>

      {/* ── Sections ────────────────────────────────────────────── */}
      <div className="px-4 space-y-3 pb-4">
        {SECTIONS.map(section => (
          <div key={section.id} className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
            <div className="px-4 py-3 bg-gray-50 border-b border-gray-100">
              <h2 className="text-sm font-black text-gray-800">{section.title}</h2>
            </div>
            <div className="px-4 py-4">
              {section.content.split('\n').map((line, i) => {
                if (!line.trim()) return <div key={i} className="h-2" />;
                if (line.startsWith('•')) {
                  return (
                    <div key={i} className="flex items-start gap-2 mb-1.5">
                      <div className="w-1.5 h-1.5 bg-gray-400 rounded-full flex-shrink-0 mt-1.5" />
                      <p className="text-xs text-gray-600 leading-relaxed">{line.slice(1).trim()}</p>
                    </div>
                  );
                }
                if (line.match(/^\d+\.\d+/)) {
                  return <p key={i} className="text-xs font-bold text-gray-700 mt-3 mb-1">{line}</p>;
                }
                return <p key={i} className="text-xs text-gray-600 leading-relaxed mb-1">{line}</p>;
              })}
            </div>
          </div>
        ))}

        {/* Governing law badge */}
        <div className="bg-gray-900 rounded-2xl px-4 py-4 relative overflow-hidden">
          <div className="absolute -top-6 -right-6 w-24 h-24 bg-white/5 rounded-full" />
          <p className="text-[10px] font-black text-white/40 uppercase tracking-widest mb-1 relative z-10">Jurisdiction</p>
          <p className="text-sm font-bold text-white relative z-10">Republic of Ghana</p>
          <p className="text-xs text-white/50 mt-0.5 relative z-10">
            Governed by Ghanaian law · Disputes resolved in Accra, Ghana
          </p>
        </div>

        {/* Footer links */}
        <div className="flex items-center justify-center gap-5 pt-2">
          <button onClick={() => onNavigate('privacy')} className="text-xs text-gray-400 hover:text-gray-600 underline">Privacy Policy</button>
          <button onClick={() => onNavigate('contact')} className="text-xs text-gray-400 hover:text-gray-600 underline">Contact Us</button>
          <button onClick={() => onNavigate('about')} className="text-xs text-gray-400 hover:text-gray-600 underline">About Us</button>
        </div>
        <p className="text-center text-[11px] text-gray-300">
          © 2025 VerifyGH Ltd. · Accra, Ghana
        </p>
      </div>
    </div>
  );
}
